-- Command names, tiers, view/cleanup constants (loaded before IKST_Shared helpers).
IKST = IKST or {}

IKST.MODULE = "IKST"
IKST.VERSION = "0.3.2.3"

IKST.STAFF_ECONOMY_GIVE_MAX = 500000
IKST.RESTORE_MAX_PERK_LEVEL = 10
IKST.QUICK_BROADCAST_MAX_LEN = 512
IKST.WAYPOINT_NAME_MAX_LEN = 64
IKST.CLAIM_LABEL_MAX_LEN = 64

IKST.CMD = {
    inspectSquare = "inspectSquare",
    cleanupObject = "cleanupObject",
    cleanupTile = "cleanupTile",
    cleanupSquare = "cleanupSquare",
    cleanupRadius = "cleanupRadius",
    cleanupCube = "cleanupCube",
    cleanupRoom = "cleanupRoom",
    cleanupBuilding = "cleanupBuilding",
    cleanupVegetation = "cleanupVegetation",
    paintPlace = "paintPlace",
    paintRemove = "paintRemove",
    vehicleSpawn = "vehicleSpawn",
    vehicleMove = "vehicleMove",
    vehicleDelete = "vehicleDelete",
    vehicleDeleteCell = "vehicleDeleteCell",
    vehiclePrune = "vehiclePrune",
    vehicleFlip = "vehicleFlip",
    vehicleRepair = "vehicleRepair",
    vehicleKey = "vehicleKey",
    vehicleList = "vehicleList",
    vehicleRelocateBackupList = "vehicleRelocateBackupList",
    vehicleRelocateRestore = "vehicleRelocateRestore",
    threatCull = "threatCull",
    threatPopulation = "threatPopulation",
    quickSave = "quickSave",
    quickBroadcast = "quickBroadcast",
    quickWater = "quickWater",
    quickPower = "quickPower",
    healSelf = "healSelf",
    feedSelf = "feedSelf",
    cureSelf = "cureSelf",
    godSelf = "godSelf",
    invisSelf = "invisSelf",
    ghostSelf = "ghostSelf",
    noclipSelf = "noclipSelf",
    tpCoords = "tpCoords",
    giveItem = "giveItem",
    giveKit = "giveKit",
    setTime = "setTime",
    setWeather = "setWeather",
    weatherMirror = "weatherMirror",
    timeMirror = "timeMirror",
    clearWeather = "clearWeather",
    clearZombies = "clearZombies",
    healTarget = "healTarget",
    kickPlayer = "kickPlayer",
    banPlayer = "banPlayer",
    bringTarget = "bringTarget",
    tpToTarget = "tpToTarget",
    giveTarget = "giveTarget",
    economyGive = "economyGive",
    economyGiveTarget = "economyGiveTarget",
    economyBalance = "economyBalance",
    economyReissueId = "economyReissueId",
    economyReissueIdTarget = "economyReissueIdTarget",
    economySnapshot = "economySnapshot",
    economySnapshotResult = "economySnapshotResult",
    economyDeposit = "economyDeposit",
    economyWithdraw = "economyWithdraw",
    economyWire = "economyWire",
    economyExchange = "economyExchange",
    economyExchangeAll = "economyExchangeAll",
    economyIdCardReissue = "economyIdCardReissue",
    economyVendEnable = "economyVendEnable",
    economyVendClaim = "economyVendClaim",
    economyShopPlace = "economyShopPlace",
    economyVendDisable = "economyVendDisable",
    economyVendSetPrice = "economyVendSetPrice",
    economyVendBuy = "economyVendBuy",
    economyVendList = "economyVendList",
    economyVendListResult = "economyVendListResult",
    economyAtmConfigure = "economyAtmConfigure",
    economyAtmPlace = "economyAtmPlace",
    economySetPref = "economySetPref",
    economyPayRequest = "economyPayRequest",
    economyPayRespond = "economyPayRespond",
    economyDelivery = "economyDelivery",
    economyPlayerBounty = "economyPlayerBounty",
    staffListPlayers = "staffListPlayers",
    vehicleRepairNear = "vehicleRepairNear",
    vehicleKeyNear = "vehicleKeyNear",
    healAll = "healAll",
    feedAll = "feedAll",
    cureAll = "cureAll",
    tpAllToMe = "tpAllToMe",
    feedTarget = "feedTarget",
    cureTarget = "cureTarget",
    godTarget = "godTarget",
    saveWaypoint = "saveWaypoint",
    delWaypoint = "delWaypoint",
    tpWaypoint = "tpWaypoint",
    listWaypoints = "listWaypoints",
    lootRepopulateContainer = "lootRepopulateContainer",
    lootRepopulateZone = "lootRepopulateZone",
    lootContainerRefresh = "lootContainerRefresh",
    autoGardener = "autoGardener",
    autoLumberjack = "autoLumberjack",
    autoGravel = "autoGravel",
    autoCorpseStack = "autoCorpseStack",
    autoHomeWreck = "autoHomeWreck",
    autoFarmer = "autoFarmer",
    autoUnloadContainers = "autoUnloadContainers",
    protectSquare = "protectSquare",
    unprotectSquare = "unprotectSquare",
    protectRadius = "protectRadius",
    unprotectRadius = "unprotectRadius",
    protectVehicle = "protectVehicle",
    unprotectVehicle = "unprotectVehicle",
    setDropbox = "setDropbox",
    setReadonly = "setReadonly",
    protectList = "protectList",
    vehicleSkinNext = "vehicleSkinNext",
    vehicleSkinPrev = "vehicleSkinPrev",
    vehicleUnlockTrunk = "vehicleUnlockTrunk",
    vehicleUnlockDoors = "vehicleUnlockDoors",
    catchTarget = "catchTarget",
    catchPlayer = "catchPlayer",
    releaseTarget = "releaseTarget",
    releasePlayer = "releasePlayer",
    toggleCreative = "toggleCreative",
    toggleUnlimitedAmmo = "toggleUnlimitedAmmo",
    lightbulbsArea = "lightbulbsArea",
    dumpPlayers = "dumpPlayers",
    dumpPlayersResult = "dumpPlayersResult",
    safehouseList = "safehouseList",
    safehouseListResult = "safehouseListResult",
    safehouseClientRefresh = "safehouseClientRefresh",
    safehouseClaimMirror = "safehouseClaimMirror",
    safehouseClaimResult = "safehouseClaimResult",
    safehouseRelease = "safehouseRelease",
    safehouseClaim = "safehouseClaim",
    safehouseTp = "safehouseTp",
    backupSafehouses = "backupSafehouses",
    restoreSafehouses = "restoreSafehouses",
    toggleSafehouseBorders = "toggleSafehouseBorders",
    vehicleClaim = "vehicleClaim",
    vehicleReleaseClaim = "vehicleReleaseClaim",
    vehicleClaimTransfer = "vehicleClaimTransfer",
    vehicleClaimSetLabel = "vehicleClaimSetLabel",
    vehicleClaimSetPerms = "vehicleClaimSetPerms",
    vehicleClaimList = "vehicleClaimList",
    vehicleClaimListResult = "vehicleClaimListResult",
    vehicleClaimMirror = "vehicleClaimMirror",
    vehicleClaimBootstrap = "vehicleClaimBootstrap",
    vehicleClaimPatch = "vehicleClaimPatch",
    vehicleClaimPing = "vehicleClaimPing",
    vehicleClaimPingResult = "vehicleClaimPingResult",
    safehouseClaimBootstrap = "safehouseClaimBootstrap",
    safehouseClaimPatch = "safehouseClaimPatch",
    safehouseClaimPing = "safehouseClaimPing",
    safehouseClaimPingResult = "safehouseClaimPingResult",
    vehicleClaimResult = "vehicleClaimResult",
    vehicleClaimNearby = "vehicleClaimNearby",
    safehouseAddMember = "safehouseAddMember",
    safehouseRemoveMember = "safehouseRemoveMember",
    safehouseInvite = "safehouseInvite",
    safehouseInviteRespond = "safehouseInviteRespond",
    safehouseInviteList = "safehouseInviteList",
    safehouseInviteListResult = "safehouseInviteListResult",
    safehouseInviteNotify = "safehouseInviteNotify",
    safehouseClaimSetPerms = "safehouseClaimSetPerms",
    safehouseSetRespawn = "safehouseSetRespawn",
    journalRecord = "journalRecord",
    journalRestore = "journalRestore",
    lockTryUnlock = "lockTryUnlock",
    lockInstallKeypad = "lockInstallKeypad",
    lockUnlockSync = "lockUnlockSync",
    setWorldRule = "setWorldRule",
    addSpriteBlacklist = "addSpriteBlacklist",
    farmRevitalize = "farmRevitalize",
    farmHarvestAll = "farmHarvestAll",
    blueprintCopy = "blueprintCopy",
    blueprintPaste = "blueprintPaste",
    createSnapshot = "createSnapshot",
    restoreSnapshot = "restoreSnapshot",
    lockSetPassword = "lockSetPassword",
    lockClear = "lockClear",
    lockTryClearance = "lockTryClearance",
    clearanceIssueSelf = "clearanceIssueSelf",
    clearanceRevokeSelf = "clearanceRevokeSelf",
    clearanceIssueTarget = "clearanceIssueTarget",
    clearanceRevokeTarget = "clearanceRevokeTarget",
    clearanceSetLock = "clearanceSetLock",
    toggleSelfCheat = "toggleSelfCheat",
    repairSelfGear = "repairSelfGear",
    resetSelfMood = "resetSelfMood",
    clearZombiesSelf = "clearZombiesSelf",
    safehouseBordersSync = "safehouseBordersSync",
    catchSync = "catchSync",
    result = "result",
    batchProgress = "batchProgress",
    vehicleListResult = "vehicleListResult",
    vehicleRelocateBackupListResult = "vehicleRelocateBackupListResult",
    inspectResult = "inspectResult",
    threatResult = "threatResult",
    staffListResult = "staffListResult",
    waypointListResult = "waypointListResult",
    applyTeleport = "applyTeleport",
    applyStaffModes = "applyStaffModes",
    applySelfCheat = "applySelfCheat",
    applyVehicleSync = "applyVehicleSync",
    protectListResult = "protectListResult",
    auditTail = "auditTail",
    auditTailResult = "auditTailResult",
    debugStatus = "debugStatus",
    debugTail = "debugTail",
    debugStatusResult = "debugStatusResult",
    debugTailResult = "debugTailResult",
    utilitySync = "utilitySync",
    rewind = "rewind",
    rewindSync = "rewindSync",
    briefingFetch = "briefingFetch",
    briefingResult = "briefingResult",
    arrivalSync = "arrivalSync",
    vehicleFieldRecovery = "vehicleFieldRecovery",
    unstuck = "unstuck",
    helpRequest = "helpRequest",
    reportPlayer = "reportPlayer",
    claimRequest = "claimRequest",
    vehicleClaimRequest = "vehicleClaimRequest",
    claimDispute = "claimDispute",
    claimRequestList = "claimRequestList",
    claimRequestListResult = "claimRequestListResult",
    claimRequestApprove = "claimRequestApprove",
    claimRequestDeny = "claimRequestDeny",
    claimRequestSetBounds = "claimRequestSetBounds",
    helpList = "helpList",
    helpResolve = "helpResolve",
    helpListResult = "helpListResult",
    dashboardSnapshot = "dashboardSnapshot",
    dashboardSnapshotResult = "dashboardSnapshotResult",
    duplicateItem = "duplicateItem",
    vehicleRefuel = "vehicleRefuel",
    vehicleRefuelNear = "vehicleRefuelNear",
    eventSet = "eventSet",
    eventClear = "eventClear",
    eventJoin = "eventJoin",
    eventReturn = "eventReturn",
    staffHistoryList = "staffHistoryList",
    staffHistoryResult = "staffHistoryResult",
    blueprintSave = "blueprintSave",
    blueprintLoad = "blueprintLoad",
    blueprintList = "blueprintList",
    blueprintDelete = "blueprintDelete",
    blueprintListResult = "blueprintListResult",
}

IKST.AUTO_COMMANDS = {
    autoGardener = true,
    autoLumberjack = true,
    autoGravel = true,
    autoCorpseStack = true,
    autoHomeWreck = true,
    autoFarmer = true,
    autoUnloadContainers = true,
}

IKST.PROTECT_COMMANDS = {
    protectSquare = true,
    unprotectSquare = true,
    protectRadius = true,
    unprotectRadius = true,
    protectVehicle = true,
    unprotectVehicle = true,
    setDropbox = true,
    setReadonly = true,
}

IKST.GUARD_COMMANDS = {
    catchTarget = true,
    catchPlayer = true,
    releaseTarget = true,
    releasePlayer = true,
    toggleCreative = true,
    toggleUnlimitedAmmo = true,
    lightbulbsArea = true,
    dumpPlayers = true,
    safehouseList = true,
    safehouseRelease = true,
    safehouseClaim = true,
    safehouseTp = true,
    backupSafehouses = true,
    restoreSafehouses = true,
    toggleSafehouseBorders = true,
    vehicleClaim = true,
    vehicleReleaseClaim = true,
    vehicleClaimTransfer = true,
    vehicleClaimSetLabel = true,
    vehicleClaimSetPerms = true,
    vehicleClaimList = true,
    vehicleClaimNearby = true,
    safehouseAddMember = true,
    safehouseRemoveMember = true,
    safehouseInvite = true,
    safehouseInviteRespond = true,
    safehouseInviteList = true,
    safehouseClaimSetPerms = true,
    safehouseSetRespawn = true,
}

IKST.PLAYER_CLAIM_COMMANDS = {
    vehicleClaim = true,
    vehicleReleaseClaim = true,
    vehicleClaimList = true,
    vehicleClaimNearby = true,
    vehicleClaimSetLabel = true,
    vehicleClaimSetPerms = true,
    safehouseClaim = true,
    safehouseList = true,
    safehouseRelease = true,
    safehouseAddMember = true,
    safehouseRemoveMember = true,
    safehouseInvite = true,
    safehouseInviteRespond = true,
    safehouseInviteList = true,
    safehouseClaimSetPerms = true,
    safehouseSetRespawn = true,
    journalRecord = true,
    journalRestore = true,
    lockTryUnlock = true,
    lockInstallKeypad = true,
}

-- Creating a claim is staff-only unless the matching self-service sandbox flag is on.
IKST.PLAYER_CLAIM_CREATE = {
    vehicleClaim = true,
    safehouseClaim = true,
}

-- Owners may list/release/edit staff-approved claims without self-service.
IKST.PLAYER_CLAIM_MANAGE = {
    vehicleReleaseClaim = true,
    vehicleClaimList = true,
    vehicleClaimNearby = true,
    vehicleClaimSetLabel = true,
    vehicleClaimSetPerms = true,
    safehouseList = true,
    safehouseRelease = true,
    safehouseAddMember = true,
    safehouseRemoveMember = true,
    safehouseInvite = true,
    safehouseInviteRespond = true,
    safehouseInviteList = true,
    safehouseClaimSetPerms = true,
    safehouseSetRespawn = true,
}

IKST.CLEARANCE_CARD_TYPE = "IKST.ClearanceTag"

IKST.JOURNAL_TYPE = "IKST.RecoveryJournal"
IKST.KEYPAD_KIT_TYPE = "IKST.KeypadKit"

IKST.STAFF_COMMANDS = {
    healSelf = true,
    feedSelf = true,
    cureSelf = true,
    godSelf = true,
    invisSelf = true,
    ghostSelf = true,
    noclipSelf = true,
    tpCoords = true,
    toggleSelfCheat = true,
    repairSelfGear = true,
    resetSelfMood = true,
    clearZombiesSelf = true,
    clearanceIssueSelf = true,
    clearanceRevokeSelf = true,
    clearanceIssueTarget = true,
    clearanceRevokeTarget = true,
    giveItem = true,
    duplicateItem = true,
    giveKit = true,
    setTime = true,
    setWeather = true,
    clearWeather = true,
    clearZombies = true,
    healTarget = true,
    bringTarget = true,
    tpToTarget = true,
    giveTarget = true,
    economyGive = true,
    economyGiveTarget = true,
    economyBalance = true,
    economyReissueId = true,
    economyReissueIdTarget = true,
    vehicleRepairNear = true,
    vehicleKeyNear = true,
    healAll = true,
    feedAll = true,
    cureAll = true,
    tpAllToMe = true,
    feedTarget = true,
    cureTarget = true,
    godTarget = true,
    saveWaypoint = true,
    delWaypoint = true,
    tpWaypoint = true,
    eventSet = true,
    eventClear = true,
    helpList = true,
    helpResolve = true,
    claimRequestList = true,
    claimRequestApprove = true,
    claimRequestDeny = true,
    claimRequestSetBounds = true,
    staffHistoryList = true,
}

-- Self-service commands available to any player (server re-validates).
IKST.PLAYER_SELF_COMMANDS = {
    unstuck = true,
    helpRequest = true,
    reportPlayer = true,
    claimRequest = true,
    vehicleClaimRequest = true,
    claimDispute = true,
    dashboardSnapshot = true,
    eventJoin = true,
    eventReturn = true,
}

-- Handled in IKST_Server (not STAFF / GUARD / PLAYER_SELF).
IKST.CORE_COMMANDS = {
    threatCull = true,
    threatPopulation = true,
    quickWater = true,
    quickPower = true,
    briefingFetch = true,
    vehicleClaimPing = true,
    safehouseClaimPing = true,
}

-- Staff-gated commands handled in IKST_Server (not IKST.STAFF_COMMANDS).
IKST.CORE_STAFF_COMMANDS = {
    quickSave = true,
    quickBroadcast = true,
    staffListPlayers = true,
    listWaypoints = true,
    auditTail = true,
    debugStatus = true,
    debugTail = true,
}

IKST.VIEW = {
    favorites = "favorites",
    hub = "favorites",
    utilities = "utilities",
    claim = "claim",
    everyone = "everyone",
    tiles = "tiles",
    vehicles = "vehicles",
    build = "build",
    server = "server",
    quick = "quick",
    players = "players",
    safehouses = "safehouses",
    worldedit = "worldedit",
    rules = "rules",
    gadgets = "gadgets",
    cleanup = "cleanup",
    painter = "painter",
    vehicle = "vehicle",
    threat = "threat",
    inspector = "inspector",
    staff = "staff",
    economy = "economy",
    automation = "automation",
    loot = "loot",
    admin = "admin",
    protect = "guard",
    guard = "guard",
}

IKST.CLEANUP_MODES = {
    removeObject = "removeObject",
    removeTile = "removeTile",
    clearSquare = "clearSquare",
    radius = "radius",
    room = "room",
    building = "building",
    vegetation = "vegetation",
    inspect = "inspect",
}

IKST.CLEANUP_SCOPES = {
    single = "single",
    cube = "cube",
    radius = "radius",
    room = "room",
    building = "building",
    cell = "cell",
}

IKST.RADIUS_PRESETS = { S = 3, M = 7, L = 15 }
IKST.CUBE_PRESETS = { S = 1, M = 3, L = 7 }

-- Core cleanup actions shown in the UI (scope is chosen separately).
IKST.CLEANUP_ACTIONS = {
    IKST.CLEANUP_MODES.removeObject,
    IKST.CLEANUP_MODES.removeTile,
    IKST.CLEANUP_MODES.vegetation,
}

IKST.CLEANUP_SCOPE_LIST = {
    IKST.CLEANUP_SCOPES.single,
    IKST.CLEANUP_SCOPES.cube,
    IKST.CLEANUP_SCOPES.radius,
    IKST.CLEANUP_SCOPES.room,
    IKST.CLEANUP_SCOPES.building,
}

IKST.PAINTER_MODES = {
    eyedropper = "eyedropper",
    paint = "paint",
    wall = "wall",
    remove = "remove",
    replace = "replace",
}
